### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Gallivant** [megaboich/js-map-parser#4]
Have installed this on NotePad++. Excellent, very good work and much better than the built in View / Function List command. However I have three issues:
1. When I shut down NotePad with the JSMapParser plug-in active, then restart NotePad, MapParser is no longer active. All other plug-ins that are active when NotePad shuts down, are active when it is restarted.
2. I can see how to change the font size of tagged function names, but there does not seem to be a way to change the font-size of all other non-tagged functions. This is a shame as 8 point is is a little small for my eyes.
3. I can't figure out how to make the ToDo list show at the bottom of the NetParser window, as per your documentation. I had the same trouble with the NetParser plug-in for Visual Studio 2015

Thanks

**Comment by megaboich** [comment]
Hi Gallivant,

I've fixed 1 and 2.
About 3: Todo list should be shown automatically it there is at least one \todo: comment.

https://github.com/megaboich/js-map-parser/releases/tag/4.1
