### ISSUE TITLE
Ignores last comma in json 

### ISSUE THREAD

**Issue by spatelengg** [megaboich/js-map-parser#5]
latest version does not show error message when there is comma at the end of json object.

e.g.
`{
    a: 'abc',
    b: 'xyz',
}
`

above syntax shows error in previous version but not in current version.

**Comment by megaboich** [comment]
That is because I have updated parsing engine to ES6 standart. Looks like this extra comma is not considered an error anymore. Yes, I know that legacy versions of IE didn't accept that, but JsMapParser isn't error checking tool - its goal is to provide map for your code and improve navigation.
