### ISSUE TITLE
Unknown exception with JsMapParser.NppPlugin.dll v4.1

### ISSUE THREAD

**Issue by JohnGoldsmith** [megaboich/js-map-parser#9]
Hi,

I'm getting an 'Unknown exception' from Notepad++ (7.2.2) when opening the app, after dropping the JsMapParser.NppPlugin.dll (4.1) into the `C:\Program Files (x86)\Notepad++\plugins` folder.  After the expection message the app starts ok although opening the Plugin manager window crashes the app.  Removing the dll from the plugins folder resolves the problem.

Best regards

John

**Comment by megaboich** [comment]
Yes, I can reproduce it with 7.2.2 on my machine.
Something must be wrong, I'll check.

**Comment by chcg** [comment]
@JohnGoldsmith 
Fixed in source/JsParser.NppPlugin/NppPluginBaseInfrastructure/NppPluginBaseExports.cs with https://github.com/megaboich/js-map-parser/pull/15.

See https://github.com/megaboich/js-map-parser/releases/tag/4.2
